[testServer]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = testExchange
QUEUE = testQueue
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[dmzServer]
BROKER_HOST = 127.0.0.1  
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = apiExchange
QUEUE = apiQueue
EXCHANGE_TYPE = direct
ROUTING_KEY = api_routing_key  ; for direct exchange type?
AUTO_DELETE = false